version: '3'

services:
  db:
    image: mysql:latest
    container_name: laravel_db
    ports:
      - "3306:3306"  # Map port 3306 on host to port 3306 in container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: kaue
      MYSQL_PASSWORD: kaue

networks:
  default:
    external: true
    name: laravel
    driver: bridge 
  